/* ==========================================================================
   DEMO CATALOGUE
   Categories, brands and products mirror the real K2 Fitness Maniacs range
   (fitnessmaniacs.com.cy). Prices marked "verified" were taken from the live
   site; the rest are realistic placeholders for the demo. Product imagery is
   drawn as SVG (see components/ProductArt.jsx) so the demo needs no photos —
   swap in real photography by adding an `image` field to any product.
   ========================================================================== */

export const CATEGORIES = [
  { slug: 'proteins', en: 'Proteins', el: 'Πρωτεΐνες', form: 'tub' },
  { slug: 'creatines', en: 'Creatines', el: 'Κρεατίνες', form: 'tub' },
  { slug: 'pre-workouts', en: 'Pre-Workouts', el: 'Pre-Workout', form: 'tub' },
  { slug: 'amino-acids', en: 'Amino Acids', el: 'Αμινοξέα', form: 'tub' },
  { slug: 'fat-burners', en: 'Fat Burners', el: 'Λιποδιαλύτες', form: 'bottle' },
  { slug: 'testosterone-boosters', en: 'Testosterone Boosters', el: 'Τεστοστερόνη', form: 'bottle' },
  { slug: 'vitamins', en: 'Vitamins', el: 'Βιταμίνες', form: 'bottle' },
  { slug: 'recoveries', en: 'Recovery', el: 'Αποκατάσταση', form: 'tub' },
  { slug: 'electrolytes', en: 'Electrolytes', el: 'Ηλεκτρολύτες', form: 'sachet' },
  { slug: 'protein-bars', en: 'Protein Bars', el: 'Μπάρες Πρωτεΐνης', form: 'bar' },
  { slug: 'energy-gels', en: 'Energy Gels', el: 'Ενεργειακά Gel', form: 'sachet' },
  { slug: 'energy-drinks', en: 'Energy Drinks', el: 'Ενεργειακά Ποτά', form: 'can' },
  { slug: 'health-beauty', en: 'Health & Beauty', el: 'Υγεία & Ομορφιά', form: 'bottle' },
]

export const SUBCATEGORIES = {
  proteins: [
    { slug: 'whey', en: 'Whey', el: 'Whey' },
    { slug: 'isolate', en: 'Isolate', el: 'Isolate' },
    { slug: 'gainers', en: 'Gainers', el: 'Gainers' },
  ],
}

export const BRANDS = [
  { slug: 'on', name: 'ON', tag: 'Optimum Nutrition' },
  { slug: 'asl', name: 'ASL', tag: 'Advanced Sport Labs' },
  { slug: 'mutant', name: 'MUTANT', tag: 'Hardcore mass' },
  { slug: 'activlab', name: 'ACTIVLAB', tag: 'Poland' },
  { slug: 'universal', name: 'UNIVERSAL', tag: 'Since 1977' },
  { slug: 'muscletech', name: 'MUSCLETECH', tag: 'Research-led' },
  { slug: 'muscle-power', name: 'MUSCLE POWER', tag: 'MP' },
  { slug: 'raw-nutrition', name: 'RAW NUTRITION', tag: 'Clean label' },
  { slug: 'stacker2', name: 'STACKER 2', tag: 'Energy' },
  { slug: 'swanson', name: 'SWANSON', tag: 'Vitamins' },
  { slug: 'hiro-lab', name: 'HIRO.LAB', tag: 'Supplements' },
  { slug: 'bmxx', name: 'BMXX', tag: 'Value range' },
]

const p = (o) => ({
  rating: 4.6,
  reviews: 18,
  stock: 12,
  sizes: [],
  flavours: [],
  badges: [],
  ...o,
})

export const PRODUCTS = [
  /* ---------------- PROTEINS ---------------- */
  p({
    id: 'asl-isolate-90',
    name: 'ASL Isolate Protein 90% — Lactose Free 908g',
    brand: 'asl',
    category: 'proteins',
    sub: 'isolate',
    price: 35,
    oldPrice: 44,
    rating: 4.9,
    reviews: 63,
    stock: 8,
    badges: ['bestseller', 'lactoseFree'],
    sizes: ['908g', '1.8kg'],
    flavours: ['Chocolate', 'Vanilla', 'Strawberry', 'Cookies'],
    macro: { protein: 27, carbs: 1.1, fat: 0.4, serving: 30 },
    en: 'Cold-filtered whey isolate at 90% protein with the lactose stripped out — the cleanest scoop on the shelf. Mixes clear, digests light, no bloat.',
    el: 'Απομονωμένη πρωτεΐνη ορού γάλακτος 90% χωρίς λακτόζη — η πιο καθαρή επιλογή του καταστήματος. Διαλύεται εύκολα, χωρίς φούσκωμα.',
  }),
  p({
    id: 'asl-beast-whey-2kg',
    name: 'ASL Beast Whey 2kg',
    brand: 'asl',
    category: 'proteins',
    sub: 'whey',
    price: 60,
    oldPrice: 72,
    rating: 4.7,
    reviews: 41,
    badges: ['bestseller'],
    sizes: ['2kg', '900g'],
    flavours: ['Chocolate', 'Banana', 'Salted Caramel'],
    macro: { protein: 24, carbs: 3.2, fat: 1.9, serving: 30 },
    en: '66 servings of straight-up whey concentrate. The workhorse tub — best price per gram of protein in Larnaca.',
    el: '66 μερίδες whey concentrate. Η καλύτερη σχέση τιμής/πρωτεΐνης στη Λάρνακα.',
  }),
  p({
    id: 'bmxx-whey-100-2000g',
    name: 'BMXX Whey 100 2000g',
    brand: 'bmxx',
    category: 'proteins',
    sub: 'whey',
    price: 60,
    rating: 4.5,
    reviews: 27,
    sizes: ['2kg'],
    flavours: ['Chocolate', 'Vanilla'],
    macro: { protein: 23, carbs: 4.1, fat: 2.2, serving: 30 },
    en: 'Solid everyday whey blend with added digestive enzymes. Great value when you are drinking two shakes a day.',
    el: 'Σταθερό καθημερινό whey με ένζυμα πέψης. Ιδανικό όταν πίνεις δύο shake την ημέρα.',
  }),
  p({
    id: 'asl-mass-gainer-5kg',
    name: 'ASL Mass Gainer 5kg',
    brand: 'asl',
    category: 'proteins',
    sub: 'gainers',
    price: 65,
    oldPrice: 79,
    rating: 4.6,
    reviews: 35,
    badges: ['flash'],
    sizes: ['5kg'],
    flavours: ['Chocolate', 'Vanilla', 'Cookies'],
    macro: { protein: 30, carbs: 88, fat: 6, serving: 150 },
    en: '1,250 kcal per serving with creatine and glutamine already in the mix. For the hard gainers who cannot eat enough.',
    el: '1.250 kcal ανά μερίδα με κρεατίνη και γλουταμίνη. Για όσους δυσκολεύονται να πάρουν βάρος.',
  }),
  p({
    id: 'on-gold-standard-whey',
    name: 'ON Gold Standard 100% Whey 2.27kg',
    brand: 'on',
    category: 'proteins',
    sub: 'whey',
    price: 89,
    rating: 4.9,
    reviews: 214,
    badges: ['bestseller'],
    sizes: ['2.27kg', '900g'],
    flavours: ['Double Rich Chocolate', 'Vanilla Ice Cream', 'Cookies & Cream'],
    macro: { protein: 24, carbs: 3, fat: 1.5, serving: 30 },
    en: 'The benchmark. 24 g protein, 5.5 g BCAAs per scoop and the mixability everything else is measured against.',
    el: 'Το σημείο αναφοράς. 24 g πρωτεΐνη, 5,5 g BCAA ανά μεζούρα.',
  }),
  p({
    id: 'mutant-mass',
    name: 'MUTANT Mass XXXTREME 2.72kg',
    brand: 'mutant',
    category: 'proteins',
    sub: 'gainers',
    price: 72,
    rating: 4.5,
    reviews: 52,
    sizes: ['2.72kg'],
    flavours: ['Triple Chocolate', 'Vanilla Ice Cream'],
    macro: { protein: 56, carbs: 192, fat: 10, serving: 320 },
    en: '2,500 calories a serving. This is the nuclear option for off-season bulking.',
    el: '2.500 θερμίδες ανά μερίδα. Η πιο δυνατή επιλογή για off-season bulking.',
  }),

  /* ---------------- CREATINES ---------------- */
  p({
    id: 'mp-creatine-500g',
    name: 'MP Creatine Monohydrate 500g',
    brand: 'muscle-power',
    category: 'creatines',
    price: 30,
    rating: 4.8,
    reviews: 88,
    badges: ['bestseller'],
    sizes: ['500g', '250g'],
    flavours: ['Unflavoured'],
    macro: { protein: 0, carbs: 0, fat: 0, serving: 5 },
    en: '100 servings of micronised monohydrate. The single most proven supplement in sport — 5 g a day, every day.',
    el: '100 μερίδες μικρονισμένης μονοϋδρικής κρεατίνης. Το πιο αποδεδειγμένο συμπλήρωμα — 5 g κάθε μέρα.',
  }),
  p({
    id: 'universal-creatine',
    name: 'Universal Creatine Powder 300g',
    brand: 'universal',
    category: 'creatines',
    price: 24,
    rating: 4.7,
    reviews: 44,
    sizes: ['300g'],
    flavours: ['Unflavoured'],
    en: 'Creapure-grade monohydrate from a brand that has been doing this since 1977.',
    el: 'Μονοϋδρική κρεατίνη ποιότητας Creapure από μια μάρκα με ιστορία από το 1977.',
  }),
  p({
    id: 'raw-creatine-hcl',
    name: 'RAW Creatine HCL 120caps',
    brand: 'raw-nutrition',
    category: 'creatines',
    price: 28,
    rating: 4.4,
    reviews: 19,
    sizes: ['120 caps'],
    en: 'Capsule form for anyone who hates the grit. No loading phase, no water retention complaints.',
    el: 'Σε κάψουλες για όσους δεν θέλουν σκόνη. Χωρίς φάση φόρτωσης.',
  }),

  /* ---------------- PRE-WORKOUTS ---------------- */
  p({
    id: 'mutant-madness',
    name: 'MUTANT Madness Pre-Workout 225g',
    brand: 'mutant',
    category: 'pre-workouts',
    price: 32,
    oldPrice: 38,
    rating: 4.7,
    reviews: 71,
    badges: ['flash'],
    sizes: ['225g'],
    flavours: ['Blue Raspberry', 'Fruit Punch', 'Sour Watermelon'],
    en: 'Stim-heavy, honest about it. Beta-alanine tingle, 300 mg caffeine, no crash at the end of the session.',
    el: 'Δυνατό pre-workout. Beta-alanine, 300 mg καφεΐνη, χωρίς πτώση ενέργειας στο τέλος.',
  }),
  p({
    id: 'activlab-pump',
    name: 'Activlab Pump Xtreme 300g',
    brand: 'activlab',
    category: 'pre-workouts',
    price: 26,
    rating: 4.4,
    reviews: 23,
    sizes: ['300g'],
    flavours: ['Lemon', 'Cola', 'Orange'],
    en: 'Citrulline-led pump formula with a lighter stim load — good for evening training.',
    el: 'Φόρμουλα pump με κιτρουλίνη και λιγότερη καφεΐνη — ιδανικό για βραδινή προπόνηση.',
  }),
  p({
    id: 'on-gold-pre',
    name: 'ON Gold Standard Pre-Workout 330g',
    brand: 'on',
    category: 'pre-workouts',
    price: 38,
    rating: 4.6,
    reviews: 57,
    sizes: ['330g'],
    flavours: ['Blueberry Lemonade', 'Green Apple'],
    en: 'Measured, clinical dosing — 175 mg caffeine, 1.5 g CarnoSyn beta-alanine, no proprietary blends.',
    el: 'Μετρημένες δόσεις — 175 mg καφεΐνη, 1,5 g CarnoSyn beta-alanine, χωρίς κρυφά μείγματα.',
  }),

  /* ---------------- AMINO ACIDS ---------------- */
  p({
    id: 'mutant-bcaa',
    name: 'MUTANT BCAA 9.7 348g',
    brand: 'mutant',
    category: 'amino-acids',
    price: 29,
    rating: 4.5,
    reviews: 36,
    sizes: ['348g'],
    flavours: ['Watermelon', 'Blue Raspberry', 'Fruit Punch'],
    en: '9.7 g of aminos per scoop with added electrolytes. Sip it through the session.',
    el: '9,7 g αμινοξέα ανά μεζούρα με ηλεκτρολύτες. Πίνε το κατά τη διάρκεια της προπόνησης.',
  }),
  p({
    id: 'activlab-eaa',
    name: 'Activlab EAA Xtra 500g',
    brand: 'activlab',
    category: 'amino-acids',
    price: 31,
    rating: 4.4,
    reviews: 21,
    sizes: ['500g'],
    flavours: ['Mojito', 'Grapefruit'],
    en: 'All nine essential aminos, not just the three. The better choice if you train fasted.',
    el: 'Και τα εννέα απαραίτητα αμινοξέα. Καλύτερη επιλογή αν προπονείσαι νηστικός.',
  }),
  p({
    id: 'universal-glutamine',
    name: 'Universal Glutamine 300g',
    brand: 'universal',
    category: 'amino-acids',
    price: 22,
    rating: 4.3,
    reviews: 14,
    sizes: ['300g'],
    flavours: ['Unflavoured'],
    en: 'Straight L-glutamine for gut health and recovery between two-a-day sessions.',
    el: 'Καθαρή L-γλουταμίνη για την πέψη και την αποκατάσταση.',
  }),

  /* ---------------- FAT BURNERS ---------------- */
  p({
    id: 'lipo-6-black',
    name: 'Lipo 6 Black 60caps',
    brand: 'muscletech',
    category: 'fat-burners',
    price: 35,
    rating: 4.6,
    reviews: 92,
    badges: ['bestseller'],
    sizes: ['60 caps'],
    en: 'The one everybody asks for by name. Strong thermogenic — start on half a cap and see how you go.',
    el: 'Το πιο δημοφιλές. Δυνατό θερμογενετικό — ξεκίνα με μισή κάψουλα.',
  }),
  p({
    id: 'activlab-machine-man-burner',
    name: 'Activlab Machine Man Burner 120caps',
    brand: 'activlab',
    category: 'fat-burners',
    price: 30,
    rating: 4.4,
    reviews: 33,
    sizes: ['120 caps'],
    en: 'Four-week cut in a bottle: caffeine, green tea, L-carnitine and chromium.',
    el: 'Καφεΐνη, πράσινο τσάι, L-καρνιτίνη και χρώμιο για τετράβδομαδο κύκλο.',
  }),
  p({
    id: 'stacker2-yohimbe',
    name: 'Stacker 2 Yohimbe Bark 100caps',
    brand: 'stacker2',
    category: 'fat-burners',
    price: 21,
    rating: 4.2,
    reviews: 17,
    sizes: ['100 caps'],
    en: 'Fasted-cardio stack staple. Take it on an empty stomach, not before bed.',
    el: 'Κλασική επιλογή για fasted cardio. Με άδειο στομάχι, όχι πριν τον ύπνο.',
  }),

  /* ---------------- TESTOSTERONE ---------------- */
  p({
    id: 'universal-animal-test',
    name: 'Universal Animal Test 21packs',
    brand: 'universal',
    category: 'testosterone-boosters',
    price: 58,
    rating: 4.5,
    reviews: 29,
    sizes: ['21 packs'],
    en: 'A three-week hormonal support cycle in daily foil packs. Nothing to weigh or count.',
    el: 'Τρίβδομαδος κύκλος ορμονικής υποστήριξης σε ημερήσια πακέτα.',
  }),
  p({
    id: 'hiro-tribulus',
    name: 'Hiro.Lab Tribulus 95% 90caps',
    brand: 'hiro-lab',
    category: 'testosterone-boosters',
    price: 19,
    rating: 4.1,
    reviews: 12,
    sizes: ['90 caps'],
    en: 'Standardised tribulus extract — the entry point for natural test support.',
    el: 'Τυποποιημένο εκχύλισμα tribulus — η βασική επιλογή φυσικής υποστήριξης.',
  }),

  /* ---------------- VITAMINS ---------------- */
  p({
    id: 'swanson-vitamin-d3',
    name: 'Swanson Vitamin D3 5000IU 250caps',
    brand: 'swanson',
    category: 'vitamins',
    price: 14,
    rating: 4.8,
    reviews: 64,
    sizes: ['250 caps'],
    en: 'Eight months of D3 for the price of two coffees. Yes, even in Cyprus most people test low in winter.',
    el: 'Οκτώ μήνες D3. Ακόμα και στην Κύπρο, οι περισσότεροι έχουν χαμηλά επίπεδα τον χειμώνα.',
  }),
  p({
    id: 'universal-animal-pak',
    name: 'Universal Animal Pak 44packs',
    brand: 'universal',
    category: 'vitamins',
    price: 42,
    rating: 4.7,
    reviews: 78,
    badges: ['bestseller'],
    sizes: ['44 packs'],
    en: 'The original training multivitamin, unchanged since 1983 because it works.',
    el: 'Η αυθεντική πολυβιταμίνη προπόνησης, αμετάβλητη από το 1983.',
  }),
  p({
    id: 'swanson-omega-3',
    name: 'Swanson Omega-3 1000mg 150caps',
    brand: 'swanson',
    category: 'vitamins',
    price: 17,
    rating: 4.6,
    reviews: 41,
    sizes: ['150 caps'],
    en: 'Molecularly distilled fish oil, no aftertaste. Joints and heart, sorted.',
    el: 'Ιχθυέλαιο μοριακής απόσταξης, χωρίς επίγευση. Για αρθρώσεις και καρδιά.',
  }),

  /* ---------------- RECOVERY ---------------- */
  p({
    id: 'on-micronised-glutamine',
    name: 'ON Micronised Glutamine 600g',
    brand: 'on',
    category: 'recoveries',
    price: 34,
    rating: 4.5,
    reviews: 26,
    sizes: ['600g'],
    flavours: ['Unflavoured'],
    en: 'Post-session recovery base. Stack it with your whey and forget about it.',
    el: 'Βάση αποκατάστασης μετά την προπόνηση. Συνδύασέ το με το whey σου.',
  }),
  p({
    id: 'raw-zma',
    name: 'RAW ZMA Night Recovery 90caps',
    brand: 'raw-nutrition',
    category: 'recoveries',
    price: 23,
    rating: 4.6,
    reviews: 31,
    sizes: ['90 caps'],
    en: 'Zinc, magnesium and B6 before bed. The cheapest sleep upgrade in the shop.',
    el: 'Ψευδάργυρος, μαγνήσιο και B6 πριν τον ύπνο. Η πιο οικονομική βελτίωση ύπνου.',
  }),

  /* ---------------- ELECTROLYTES ---------------- */
  p({
    id: 'activlab-iso-plus',
    name: 'Activlab Iso Plus Powder 1250g',
    brand: 'activlab',
    category: 'electrolytes',
    price: 18,
    rating: 4.5,
    reviews: 38,
    badges: ['summer'],
    sizes: ['1250g'],
    flavours: ['Lemon', 'Orange', 'Grapefruit'],
    en: 'Cyprus-summer essential. Sodium, potassium and magnesium that actually replace what you sweat out.',
    el: 'Απαραίτητο για το κυπριακό καλοκαίρι. Νάτριο, κάλιο και μαγνήσιο για αναπλήρωση υγρών.',
  }),
  p({
    id: 'raw-hydrate-sticks',
    name: 'RAW Hydrate Electrolyte Sticks 20x',
    brand: 'raw-nutrition',
    category: 'electrolytes',
    price: 16,
    rating: 4.4,
    reviews: 15,
    badges: ['summer'],
    sizes: ['20 sticks'],
    flavours: ['Watermelon', 'Lime'],
    en: 'Single-serve sticks for the gym bag or the beach. Zero sugar.',
    el: 'Ατομικά φακελάκια για την τσάντα του γυμναστηρίου. Χωρίς ζάχαρη.',
  }),

  /* ---------------- BARS / GELS / DRINKS ---------------- */
  p({
    id: 'mutant-iron-bar',
    name: 'MUTANT Iron Bar 24x',
    brand: 'mutant',
    category: 'protein-bars',
    price: 45,
    rating: 4.4,
    reviews: 22,
    sizes: ['Box of 24', 'Single'],
    flavours: ['Chocolate Fudge', 'Peanut Butter', 'Cookies'],
    en: '20 g protein and it actually tastes like a chocolate bar. Full box price beats singles by 30%.',
    el: '20 g πρωτεΐνη με γεύση σοκολάτας. Το κουτί είναι 30% πιο συμφέρον από τα μεμονωμένα.',
  }),
  p({
    id: 'activlab-energy-gel',
    name: 'Activlab Energy Gel 12x70g',
    brand: 'activlab',
    category: 'energy-gels',
    price: 24,
    rating: 4.3,
    reviews: 11,
    sizes: ['Box of 12'],
    flavours: ['Cherry', 'Orange'],
    en: 'For the road cyclists and the Larnaca 10K crowd. 40 g fast carbs, no chewing.',
    el: 'Για ποδηλάτες και δρομείς. 40 g γρήγοροι υδατάνθρακες, χωρίς μάσημα.',
  }),
  p({
    id: 'stacker2-energy-shot',
    name: 'Stacker 2 Energy Shot 24x60ml',
    brand: 'stacker2',
    category: 'energy-drinks',
    price: 39,
    rating: 4.2,
    reviews: 18,
    sizes: ['Tray of 24'],
    flavours: ['Berry', 'Citrus'],
    en: 'Zero-sugar shots, 200 mg caffeine each. Keep a tray at the shop counter.',
    el: 'Shots χωρίς ζάχαρη, 200 mg καφεΐνη. Ιδανικά για τον πάγκο του καταστήματος.',
  }),
  p({
    id: 'mutant-energy-can',
    name: 'MUTANT Energy 12x473ml',
    brand: 'mutant',
    category: 'energy-drinks',
    price: 33,
    rating: 4.5,
    reviews: 24,
    sizes: ['Case of 12'],
    flavours: ['Sour Slushie', 'Baja Blast', 'Mango'],
    en: 'Cold ones in the fridge at the shop. 164 mg caffeine, zero sugar.',
    el: 'Παγωμένα στο ψυγείο του καταστήματος. 164 mg καφεΐνη, χωρίς ζάχαρη.',
  }),

  /* ---------------- HEALTH & BEAUTY ---------------- */
  p({
    id: 'swanson-collagen',
    name: 'Swanson Collagen Peptides 400g',
    brand: 'swanson',
    category: 'health-beauty',
    price: 27,
    rating: 4.6,
    reviews: 34,
    sizes: ['400g'],
    flavours: ['Unflavoured'],
    en: 'Type I & III peptides for skin, hair and joints. Dissolves in coffee without clumping.',
    el: 'Πεπτίδια τύπου I & III για δέρμα, μαλλιά και αρθρώσεις. Διαλύεται στον καφέ.',
  }),
  p({
    id: 'hiro-biotin',
    name: 'Hiro.Lab Biotin + Zinc 120caps',
    brand: 'hiro-lab',
    category: 'health-beauty',
    price: 13,
    rating: 4.3,
    reviews: 16,
    sizes: ['120 caps'],
    en: 'Hair and nail support, four months per bottle.',
    el: 'Υποστήριξη για μαλλιά και νύχια, τέσσερις μήνες ανά συσκευασία.',
  }),
]

/* ---------------------------------------------------------------- helpers */

export const bySlug = (id) => PRODUCTS.find((x) => x.id === id)
export const brandOf = (slug) => BRANDS.find((b) => b.slug === slug)
export const categoryOf = (slug) => CATEGORIES.find((c) => c.slug === slug)

export const formFor = (product) => categoryOf(product.category)?.form ?? 'tub'

export const flashDeals = () => PRODUCTS.filter((x) => x.oldPrice).slice(0, 4)
export const bestsellers = () => PRODUCTS.filter((x) => x.badges.includes('bestseller'))

export const PRICE_MAX = Math.ceil(Math.max(...PRODUCTS.map((x) => x.price)) / 10) * 10
